os: osx
osx_image: xcode8.3
language: node_js
node_js:
  - 8

before_install:
  - openssl aes-256-cbc -K $encrypted_e7dd261e3971_key -iv $encrypted_e7dd261e3971_iv -in .travis/Certificates.p12.enc -out .travis/Certificates.p12 -d
  - security import .travis/Certificates.p12 -P $HEROKU_DARWIN_SIGNING_PASS
script:
  - CHANNEL=dev ./scripts/darwin/build dist
  - ls -ls dist
env:
  global:
    secure: "Lmrbyyz1WU1JSpfjxgWwAV3WcYmz5izPEEGFegzdXWUOCB2yP6Nq1UKSMLgRVK9S/myHlOVgR4gWh2RDWy+FaK4y3m3vqAPu6+o6yw4m+TtdOI6GYwbQB3Cv2JYfJVoe4GIDcWhVsZa+qVlozgNdpr8EaHpscX3IbiDmmbeWCmI="
