environment:
  nodejs_version: "9"
cache:
 - "%LOCALAPPDATA%\\Yarn" -> appveyor.yml
 - node_modules -> appveyor.yml

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
test_script:
  - bin\run.cmd version
  - bin\run.cmd help
  - .\node_modules\.bin\jest --coverage
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

build: off
