---
defaults: &defaults
  working_directory: ~/cli
  docker:
    #- image: dickeyxxx/cli-engine-docker:v2.1.0
    - image: dickeyxxx/cli-engine-docker:v2.0.1

# filters: &all_filters
#   tags: *version_tags
#   branches:
#     ignore: /.*/

version: 2
executorType: docker
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cli-{{ checksum "yarn.lock" }}
            - cli
      - run: ./scripts/build
      - run: ./scripts/test
      - save_cache:
        key: cli-{{ checksum "yarn.lock" }}
        paths:
          - /usr/local/share/.cache/yarn
          - ~/cli/node_modules
      # - type: deploy
      #   shell: /bin/bash
      #   command: |
      #     set -e
      #     echo $HEROKU_DEB_KEY | base64 -d | gpg --import
      #     set -ex
      #     ./scripts/release-wrapper deb
      #     ./scripts/copy-windows-files
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - tmp/tarballs/*
      #       - node_modules/cli-engine/bin/version
  # release_windows_x64:
  #   <<: *defaults
  #   steps:
  #     - type: checkout
  #     - attach_workspace:
  #         at: ~/cli
  #     - run: |
  #         set -ex
  #         ./scripts/extract-windows-files x64
  #         ./scripts/release-wrapper -a x64 windows
  #         ./scripts/copy-artifacts x64
  #     - store_artifacts:
  #         path: tmp/artifacts
  # release_windows_x86:
  #   <<: *defaults
  #   steps:
  #     - type: checkout
  #     - attach_workspace:
  #         at: ~/cli
  #     - run: |
  #         set -ex
  #         ./scripts/extract-windows-files x86
  #         ./scripts/release-wrapper -a x86 windows
  #         ./scripts/copy-artifacts x86
  #     - store_artifacts:
  #         path: tmp/artifacts
workflows:
  version: 2
  build_and_release:
    jobs:
      - build_and_test:
          filters:
            tags: &version_tags
              only: /^v.*/
      # - release_windows_x64:
      #     filters: *all_tags_filters
      #     requires:
      #       - build
      # - release_windows_x86:
      #     filters: *all_tags_filters
      #     requires:
      #       - build
