---
defaults: &defaults
  working_directory: ~/cli
  docker:
    - image: dickeyxxx/cli-engine-docker:v2.1.0
      environment:
        NPM_CONFIG_REGISTRY: https://cli-npm.heroku.com

version: 2
executorType: docker
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-test-{{ checksum "yarn.lock" }}
            - v2-test
      - run: ./scripts/circle/prep
      - run: ./scripts/test
      - save_cache:
          key: v2-test-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
            - ~/cli/node_modules
  darwin_x64_build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: &release_target_yarn_cache
          keys:
            - v3-release-target-yarn-{{ checksum "yarn.lock" }}
            - v3-release-target-yarn
      - restore_cache: {keys: [node-v8.3.0-darwin-x64]}
      - run: ./scripts/circle/build
      - persist_to_workspace: &persist_dist
          root: tmp/builds
          paths: [darwin_x64]
      - save_cache:
          key: v3-release-target-yarn-{{ checksum "yarn.lock" }}
          paths: [/usr/local/share/.cache/yarn]
      - save_cache: &node_cache_save
          key: node-v8.3.0-darwin-x64
          paths: [~/cli/tmp/cache/node]
  linux_x64_build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *release_target_yarn_cache
      - restore_cache: {keys: [node-v8.3.0-linux-x64]}
      - run: ./scripts/circle/build
      - persist_to_workspace: &persist_dist
          root: tmp/builds
          paths: [linux_x64]
      - save_cache:
          <<: *node_cache_save
          key: node-v8.3.0-linux-x64
  # linux_x86:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: [node-v8.3.0-linux-x86]
  #     - restore_cache: *release_target_yarn_cache
  #     - run: ./scripts/circle/build
  #     - save_cache:
  #         key: node-v8.3.0-linux-x86
  #         paths: ~/cli/tmp/cache/node
  # linux_arm:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: [node-v8.3.0-linux-arm]
  #     - restore_cache: *release_target_yarn_cache
  #     - run: ./scripts/circle/build
  #     - save_cache:
  #         key: node-v8.3.0-linux-arm
  #         paths: ~/cli/tmp/cache/node
  # windows_x64:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: [node-v8.3.0-windows-x64]
  #     - restore_cache: *release_target_yarn_cache
  #     - run: ./scripts/circle/build
  #     - save_cache:
  #         key: node-v8.3.0-windows-x64
  #         paths: ~/cli/tmp/cache/node
  # windows_x86:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: [node-v8.3.0-windows-x86]
  #     - restore_cache: *release_target_yarn_cache
  #     - run: ./scripts/circle/build
  #     - save_cache:
  #         key: node-v8.3.0-windows-x86
  #         paths: ~/cli/tmp/cache/node
  # debian:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache: *release_target_yarn_cache
  #     - run: ./scripts/linux/debian
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: {at: dist}
      - run: ./scripts/circle/release
workflows:
  version: 2
  heroku_cli:
    jobs:
      - test:
          filters: &all_pushes
            tags: &version_tags
              only: /^v.*/
      - darwin_x64_build: &build_step
          filters: *all_pushes
      - linux_x64_build: *build_step
      - release:
          filters:
            tags: *version_tags
            branches: [master, dev, streamline]
          # requires:
          #   - darwin_x64_build
          #   - linux_x64_build
# - linux_x86: *release_target
# - linux_arm: *release_target
# - windows_x64: *release_target
# - windows_x86: *release_target
# - debian:
#     filters: *release_filters
#     requires: [test]
