---

version: 2
executorType: docker
jobs:
  test:
    docker: &windows_docker
      - image: dickeyxxx/cli-engine-docker:v2.1.0
        environment: &env
          NPM_CONFIG_REGISTRY: https://cli-npm.heroku.com
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v2-test-{{ checksum "yarn.lock" }}
      #       - v2-test
      - run: ./scripts/prep
      - run: ./scripts/test
      - save_cache:
          key: v2-test-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
            - ~/cli/node_modules
  build_darwin_x64:
    docker: &node_docker
      - image: node:8.4
        environment: *env
    steps:
      - checkout
      # - restore_cache: &release_target_yarn_cache
      #     keys:
      #       - v3-release-target-yarn-{{ checksum "yarn.lock" }}
      #       - v3-release-target-yarn
      # - restore_cache: {keys: [node-v8.3.0-darwin-x64]}
      - run: ./scripts/build/darwin
      - persist_to_workspace: &persist_workspace
          root: tmp
          paths: [darwin_x64/dist]
      - save_cache:
          key: v3-release-target-yarn-{{ checksum "yarn.lock" }}
          paths: [/usr/local/share/.cache/yarn]
      - save_cache: &node_cache_save
          key: node-v8.3.0-darwin-x64
          paths: [~/cli/tmp/cache/node]
  build_linux_x64:
    docker: *node_docker
    steps:
      - checkout
      - run: ./scripts/build/linux
      - persist_to_workspace:
          <<: *persist_workspace
          paths: [linux_x64/dist]
  build_linux_x86:
    docker: *node_docker
    steps:
      - checkout
      - run: ./scripts/build/linux
      - persist_to_workspace:
          <<: *persist_workspace
          paths: [linux_x86/dist]
  build_linux_arm:
    docker: *node_docker
    steps:
      - checkout
      - run: ./scripts/build/linux
      - persist_to_workspace:
          <<: *persist_workspace
          paths: [linux_arm/dist]
  build_windows_x64:
    docker: *windows_docker
    steps:
      - checkout
      - run: ./scripts/build/windows
      - persist_to_workspace:
          <<: *persist_workspace
          paths: [windows_x64/dist]
  build_windows_x86:
    docker: *windows_docker
    steps:
      - checkout
      - run: ./scripts/build/windows
      - persist_to_workspace:
          <<: *persist_workspace
          paths: [windows_x86/dist]
  release:
    docker:
      - image: dickeyxxx/cli-engine-docker:v3.0.3
        environment: *env
    steps:
      - checkout
      - attach_workspace:
          at: tmp
      - run: ls tmp
      - run: ./scripts/release/circle
  # debian:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache: *release_target_yarn_cache
  #     - run: ./scripts/linux/debian
workflows:
  version: 2
  heroku_cli:
    jobs:
      - test:
          filters: &all_pushes
            tags: &version_tags
              only: /^v.*/
      - build_darwin_x64: &build_step
          filters: *all_pushes
      - build_linux_x64: *build_step
      - build_linux_x86: *build_step
      - build_linux_arm: *build_step
      - build_windows_x64: *build_step
      - build_windows_x86: *build_step
      - release:
          filters:
            tags: *version_tags
            branches:
              only:
                - master
                - dev
                - streamline
          requires:
            - test
            - build_darwin_x64
            - build_linux_x64
            - build_linux_x86
            - build_linux_arm
            - build_windows_x64
            - build_windows_x86
# - debian:
#     filters: *release_filters
#     requires: [test]
