---
defaults: &defaults
  working_directory: ~/cli
  docker:
    - image: dickeyxxx/cli-engine-docker:v2.1.0

version: 2
executorType: docker
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-test-{{ checksum "yarn.lock" }}
            - v1-test
      - run: ./scripts/circle/build
      - run: ./scripts/test
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
      - save_cache:
          key: v1-test-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
            - ~/cli/node_modules
  darwin_x64: &release_target_job
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            - v1-yarn
      - run: ./scripts/circle/release
      - save_cache:
          key: v1-release-target-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
            - ~/cli/tmp/cache
  linux_x64: *release_target_job
  linux_x86: *release_target_job
  linux_arm: *release_target_job
  windows_x64: *release_target_job
  windows_x86: *release_target_job
  postrelease:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/circle/postrelease
workflows:
  version: 2
  heroku_cli:
    jobs:
      - test:
          filters:
            tags: &version_tags
              only: /^v.*/
      - darwin_x64: &release_target
          filters:
            tags: *version_tags
            branches:
              only:
                - master
                - dev
                - macos-installer
          requires:
            - test
      - linux_x64: *release_target
      - linux_x86: *release_target
      - linux_arm: *release_target
      - windows_x64: *release_target
      - windows_x86: *release_target
      - postrelease:
          requires:
            - darwin_x64
            - linux_x64
            - linux_x86
            - linux_arm
            - windows_x64
            - windows_x86
