---
defaults: &defaults
  working_directory: ~/cli
  docker:
    #- image: dickeyxxx/cli-engine-docker:v2.1.0
    - image: dickeyxxx/cli-engine-docker:v2.0.1

# filters: &all_filters
#   tags: *version_tags
#   branches:
#     ignore: /.*/

version: 2
executorType: docker
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: &yarn_cache
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn
      - restore_cache: &node_modules_cache
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            - node-modules
      - run: ./scripts/circle/build
      - run: ./scripts/test
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/cli/node_modules
  macos:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *yarn_cache
      - run: OS=darwin ARCH=x64 ./scripts/circle/release
  # release_windows_x64:
  #   <<: *defaults
  #   steps:
  #     - type: checkout
  #     - attach_workspace:
  #         at: ~/cli
  #     - run: |
  #         set -ex
  #         ./scripts/extract-windows-files x64
  #         ./scripts/release-wrapper -a x64 windows
  #         ./scripts/copy-artifacts x64
  #     - store_artifacts:
  #         path: tmp/artifacts
  # release_windows_x86:
  #   <<: *defaults
  #   steps:
  #     - type: checkout
  #     - attach_workspace:
  #         at: ~/cli
  #     - run: |
  #         set -ex
  #         ./scripts/extract-windows-files x86
  #         ./scripts/release-wrapper -a x86 windows
  #         ./scripts/copy-artifacts x86
  #     - store_artifacts:
  #         path: tmp/artifacts
workflows:
  version: 2
  heroku_cli:
    jobs:
      - test:
          filters: &all_pushes
            tags: &version_tags
              only: /^v.*/
      - macos: &release_target
          filters: *all_pushes
          requires:
            - test
      - linux: *release_target
      - windows: *release_target
      - postrelease:
          filters: *all_pushes
          requires:
            - macos
            - linux
            - windows
      # - release_windows_x64:
      #     filters: *all_tags_filters
      #     requires:
      #       - build
      # - release_windows_x86:
      #     filters: *all_tags_filters
      #     requires:
      #       - build
