name: heroku
version: git
summary: Heroku CLI
description: Heroku CLI
grade: stable
confinement: classic

apps:
  heroku:
    command: bin/run

parts:
  heroku:
    plugin: nil
    install: |
      curl -o- -L https://yarnpkg.com/install.sh | bash
      yarn
      yarn pack --filename heroku.tar.gz
      tar -xzf heroku.tar.gz
      rmdir ../install
      mv package ../install
      cd ../install && yarn --prod
      cd ../install && bin/run -v
